---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynatrace-op-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster-local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-dynatrace-operator'
    spec:
      destination:
        namespace: dynatrace
        server: '{{url}}'
      project: default
      source:
        repoURL: 'https://github.com/luiscachog/ocp4-gitops'
        path: common-base/dynatrace
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
