---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: file-integrity-appset
  namespace: openshift-gitops
spec:
  generators:
    - lists:
        elements:
        - cluster: in-cluster-local
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}-file-integrity'
    spec:
      destination:
        namespace: openshift-file-integrity
        server: '{{server}}'
      project: default
      source:
        path: 'common-base/openshift-file-integrity'
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
