---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-logging-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster-local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-openshift-logging'
    spec:
      destination:
        namespace: openshift-logging
        server: '{{url}}'
      project: default
      source:
        path: 'common-base/openshift-logging'
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - cluster-logging-operator
